# (PART) Cours I: visualisation et inférence {-}

# Introduction {#intro}

**Contenu provisoire, à retravailler en fonction d'un canevas commun aux différents modules.**

L'objectif de ce module est de motiver les étudiants pour apprendre les outils qui leur permettront de faire de la science des données. nous n'entrerons pas directement dans le vif du sujet, mais nous initierons une activité plus _ludique_, mais néanmoins utile et qui leur permettra de faire connaissance avec divers outils logiciels dont Git, Markdown, RStudio, Blogdown, ... Il s'agira de réaliser son propre **site web professionnel** avec `blogdown` et un dépôt Github.

Les acquis recherchés ici sont:

- Appréhender ce qu'est la science des données et les (bio)statistiques.
- S'initier à des outils de base (SciViews Box, RStudio, Markdown, git, Github).
- Se sensibiliser à l'importance d'une présence web au niveau professionnel.

Un template `blogdown` sera fourni dans Github Classroom. Il sera également expliqué qu'un "bookdown" collectif sera créé, et pourra être complété par les étudiants avec du matériel qu'ils créeront eux-mêmes, ou des liens vers des sites intéressants qu'ils découvriront au cours de leur apprentissage. Concernant ces éléments concrets, un débriefing sera prévu concernant la participation au "bookdown" au module #11.

**Idées provisoires:**

- Fournir un document qui explique comment on passe du document R Markdown à la version finale, grâce à **knitr** [@R-knitr; @xie2015].

- **Présentation 1h**, installation de SciViews Box sur les machines du labo et présentation de RStudio + projet + un document markdown + ajouter git et montrer l'intérêt, suivi d'une "install party" (temps prévu après le cours), quelques jours où ils ont à digérer la matière, voir Markdown et créer un compte Github, 2h pour créer le site web blogdown.

- Ensuite, il faut du matériel qui présente git, github, clone, commit, push, pull, fetch, ... comme capsule à étudier après le cours

- Début de module suivant (participation cotée): réexpliquer avec ses propres mots git + Github.

- Leur expliquer les changements. Comment le monde était il y a 25 ans? Pas d'internet, pas de smartphone. Que feraient-ils sans smartphone.

- Les révolutions indistrielles:
    * 1770 (1756) révolution 1: mécanisation
    * 1870 révolution 2: maîtrise de l'énergie
    * 1970 (1979) révolution 3: informatique
    * 1990 révolution 4: internet (1990 Web, 1992 ISOC = Internet society, 1993 = premuer browser web)
    * 2000 révolution 5: numérique. GAFA = Google - Apple - Facebook - Amazon + Microsoft = GAFAM aux USA et BATX en Chine = Baidu - Alibaba - Tencent - Xiaomi. Aussi NATU = Netflix - Airbnb - Tesla - Uber.
    2010 révolution 6: NBIC = nanotechnologies - biotechnologies - informatique - sciences cognitives.
    2020 = date prévue pour que l'ordinateur ait la même puissane de traitement de l'information que le cerveau humain
    2030 = transhumanisme: ordinateur plus puissant que l'homme et le remplaçant.

- Valeur estimée des données et informations mises à disposition par les utilisateurs du net: 1000 milliards de dollar par an (écrire en chiffres)!

- En 2020, quantité d'information ajoutée sur le net: 1000 milliards de milliards par semaine (écrire en chiffre aussi)

- Comparaison de puissance de traitement du cerveau humain _versus_ l'ordinateur: 89 milliards de neurones, mais travail en multitâche alors qu'un processeur est monotâche => difficile à comparer. Une étude a montré en 2017 que l'un des 5 ordinateurs les plus puissants a été capable de simuler le fonctionnement d'environ 1% du cerveau humain en 1 sec. Il lui a fallu 40 min de calcul pour y arriver. Intel estime que l'évolution permettra d'égaler le cerveau humain en terme de vitesse de traitement vers 2020.

- Consommation du supercalculateur: en mégawatts, alors que le cerveau humain consomme 12-13W seulement!

- "Le **transhumanisme** est une approche interdisciplinaire qui nous amène à comprendre et à évaluer les avenues qui nous permettrons de surmonter nos limites biologiques par les progrès technologiques. Les transhumanistes cherchent à développer les possibilités techniques afin que les gens vivent plus longtemps et ..."

